apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: machine-csr-noop.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Simple Controller to link Machine and Node for CSR Approvals
  displayName: Machine Node Noop
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - machine
  - machine-api
  - csr-approver
  links:
  - name: Machine Node Noop
    url: github.com/csfreak/machine-csr-noop
  maintainers:
  - email: github@csfreak.com
    name: Jason Ross
  maturity: alpha
  provider:
    name: Jason Ross
  replaces: machine-csr-noop.v0.1.10
