
name: Release

on:
  push:
    branches:
      - main
    
jobs:
  Release:
    name: Creates Tag and Release Artifacts and Upload to Quay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
          
      - name: Get Semantic Version
        id: v
        uses: PaulHatch/semantic-version@v4.0.3
         with:
          short_tags: false
     
     - name: Tag Release
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.v.outputs.version_tag }}"
        
      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      
      - name: Builds
        env:
          VERSION: "${{ steps.v.outputs.version_tag }}"
        run: |
          make manifests
          make generate
          make build
          make docker-build
          make bundle
          make bundle-build
          make catalog-build
      - name: Push Builds
        env:
          VERSION: "${{ steps.v.outputs.version_tag }}"
        run:
          make docker-push
          make bundle-push
          make catalog-push
